// <auto-generated />
using System;
using MediTrack.ReminderService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediTrack.ReminderService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReminderDbContext))]
    [Migration("20260618045731_ChangePatientIdToInt")]
    partial class ChangePatientIdToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MediTrack.ReminderService.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("channel");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("delivery_status");

                    b.Property<long>("ReminderId")
                        .HasColumnType("bigint")
                        .HasColumnName("reminder_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId")
                        .HasDatabaseName("ix_notification_log_reminder");

                    b.ToTable("notification_log", (string)null);
                });

            modelBuilder.Entity("MediTrack.ReminderService.Domain.Entities.NotificationPreference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("GlobalEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("global_enabled");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int>("RepeatCount")
                        .HasColumnType("int")
                        .HasColumnName("repeat_count");

                    b.Property<bool>("SoundEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sound_enabled");

                    b.Property<bool>("VibrationEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("vibration_enabled");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasDatabaseName("ux_notification_preference_patient");

                    b.ToTable("notification_preference", (string)null);
                });

            modelBuilder.Entity("MediTrack.ReminderService.Domain.Entities.Reminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("body");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cancelled_at");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("entity_type");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "Status")
                        .HasDatabaseName("ix_reminder_patient_status");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("ix_reminder_status_scheduled");

                    b.HasIndex("PatientId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_reminder_patient_entity");

                    b.ToTable("reminder", (string)null);
                });

            modelBuilder.Entity("MediTrack.ReminderService.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_outbox_processed_at");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("MediTrack.ReminderService.Infrastructure.Persistence.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId");

                    b.ToTable("processed_event", (string)null);
                });

            modelBuilder.Entity("MediTrack.ReminderService.Domain.Entities.NotificationLog", b =>
                {
                    b.HasOne("MediTrack.ReminderService.Domain.Entities.Reminder", null)
                        .WithMany("NotificationLogs")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediTrack.ReminderService.Domain.Entities.Reminder", b =>
                {
                    b.Navigation("NotificationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
